---
- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Apache (httpd) installieren
      yum:
        name: httpd
        state: present

    - name: Apache starten und beim Booten aktivieren
      service:
        name: httpd
        state: started
        enabled: true

    - name: Einfache Startseite bereitstellen
      copy:
        dest: /var/www/html/index.html
        mode: '0644'
        content: |
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Hello from Amazon Linux EC2 with Apache Webserver</title>
            </head>
            <body style="font-family: Arial, sans-serif; text-align: center; margin-top: 80px;">
              <h1 style="margin: 10px 0;">Provisioned with Terraform</h1>
              <h1 style="margin: 10px 0;">Configured with Ansible</h1>
              <h1 style="margin: 10px 0;">Deployed with Jenkins</h1>
            </body>
          </html>
